Repository project-mirai/mirai-api-http, pull requests merged in 2021-04, with the labels that each got.

#297 添加支持设置精华消息
  README.md
  docs/API.md
  mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/MessageRouteModule.kt
Labels: Feature, code-ready

#300 Add member nick in `/memberInfo`
  docs/API.md
  mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/GroupManageRouteModule.kt
Labels: Feature, code-ready

#294 加入文件操作
  README.md
  docs/API.md
  docs/MessageType.md
  mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/HttpApiPluginBase.kt
  mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/FileDTO.kt
  mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/MessageDTO.kt
  mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/BaseRoute.kt
  mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
  mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/InfoRouteModule.kt
Labels: Feature, code-ready

#315 doc: 上传文件缺失 target 参数
  docs/API.md
Labels: bug

#311 修复文件 API, 添加新建目录
  docs/API.md
  mirai-api-http/build.gradle.kts
  mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
Labels: bug, code-ready

#320 Add support to MusicShare
  docs/MessageType.md
  mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/MessageDTO.kt
Labels: Feature
